# Generated by Django 5.0.3 on 2025-04-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='otp_code',
            new_name='otp',
        ),
    ]
