# Generated by Django 5.1.7 on 2025-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='database_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='database_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
