# Generated by Django 5.0.3 on 2025-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_database_id_session_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
