# Generated by Django 5.2 on 2025-04-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshipmetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
