# Generated by Django 5.0.3 on 2025-04-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_alter_relationshipmetadata_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_data', models.JSONField(help_text='JSON representation of the ER diagram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='er_diagram', to='databases.clientdatabase')),
            ],
        ),
    ]
